version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    ports:
      - "5000:80"
    volumes:
      - ./web:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 400M
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp1_db
      MYSQL_USER: hanlinh
      MYSQL_PASSWORD: crosemont
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
